environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - QT5: C:\Qt\5.10.1\mingw53_32
    
branches:
  only:
    - master

install:
  - set Path=%QT5%\bin;%Path%
  - choco install -y InnoSetup

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%
 - qmake
 - mingw32-make
 
after_build:
  - iscc big-file-editor-installer.iss

artifacts:
 - path: setupbigfileeditor.exe
