image: Visual Studio 2017

install:
  - set Path=%QT5%\bin;%Path%
  - choco install -y InnoSetup

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - C:\Qt\5.9\msvc2017_64\bin\qmake.exe -tp vc
  
after_build:
  - iscc big-file-editor-installer.iss
  - move Output\setupbigfileeditor.exe .

artifacts:
 - path: setupbigfileeditor.exe

deploy:
  description: 'Windows Release'
  provider: GitHub
  auth_token:
    secure: wKYGmYxyZoGANT1qraz3HzsUN9tiYx9pvF3KpILJZ/UQtC+EC5XHsnxKNtCjDUhb # your encrypted token from GitHub
  artifact: /.*\.exe/
  on:
    appveyor_repo_tag: false        # deploy on tag push only
