image: Visual Studio 2017

install:
  - set Path=%QT5%\bin;%Path%
  - choco install -y InnoSetup

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64
  - C:\Qt\5.9\msvc2017_64\bin\qmake.exe -tp vc
  
after_build:
  - iscc big-file-editor-installer.iss
  - move Output\setupbigfileeditor.exe .

artifacts:
 - path: setupbigfileeditor.exe

deploy:
  release: BigFileEditor-v$(appveyor_build_version)
  description: 'Auto build from appveyor'
  provider: GitHub
  auth_token:
    secure: df931bfdc9caf87a30c084ef7a81ee0b5b481906 # your encrypted token from GitHub
  artifact: setupbigfileeditor.exe
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
