environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  matrix:
  - CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"
    QT5: C:\Qt\5.9.4\msvc2017_64
    
branches:
  only:
    - master

install:
  - set Path=%QT5%\bin;%Path%
  - choco install -y InnoSetup

build_script:
 - cd %APPVEYOR_BUILD_FOLDER%
 - dir
 - set
 - qmake 
 
after_build:
  - iscc big-file-editor-installer.iss

artifacts:
 - path: setupbigfileeditor.exe
