branches:
  only:
    - master
    - devel

install:
  - set QTDIR=C:\Qt\5.10.1\msvc2017_64
  - choco install -y InnoSetup
  - set PATH=%QTDIR%\bin;%QTDIR%\bin;%PATH%;"C:\Program Files (x86)\Inno Setup 5"
build_script:
  - qmake big-file-editor.pro
  - %make%
after_build:
  - iscc big-file-editor-installer.iss

artifacts:
 - path: *-win64.exe
   name: Win64Installer
 - path: *-win32.exe
   name: Win32Installer
