image: Visual Studio 2022

install:
  - CALL "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - SET PATH=%PATH%;C:\Qt\5.15\msvc2019_64\bin;%CACHE_DIR%\jom
  - choco install -y InnoSetup

build_script:
  - qmake big-file-editor.pro
  - make
  - del /q release\*.h release\*.cpp release\*.o
  - windeployqt release\big-file-editor.exe
  
after_build:
  - iscc big-file-editor-installer.iss
  - move Output\setupbigfileeditor.exe .

artifacts:
 - path: setupbigfileeditor.exe

deploy:
  description: 'Windows Release'
  provider: GitHub
  auth_token:
    secure: DfVhtXbEs+QEXip7f+Pt9Yon1UeYhlFnJpcY9yu3rhyg4bIOe7vUwEC5+zMbQTJt # your encrypted token from GitHub
  artifact: /.*\.exe/
  on:
    appveyor_repo_tag: false        # deploy on tag push only
