install:
  - set Path=C:\Qt\5.13.0\mingw73_64\bin;C:\QT\Tools\mingw730_64\bin;%Path%
  - choco install -y InnoSetup

build_script:
  - qmake big-file-editor.pro CONFIG+=static
  - mingw32-make
  
after_build:
  - iscc big-file-editor-installer.iss
  - move Output\setupbigfileeditor.exe .

artifacts:
 - path: setupbigfileeditor.exe

deploy:
  description: 'Windows Release'
  provider: GitHub
  auth_token:
    secure: DfVhtXbEs+QEXip7f+Pt9Yon1UeYhlFnJpcY9yu3rhyg4bIOe7vUwEC5+zMbQTJt # your encrypted token from GitHub
  artifact: /.*\.exe/
  on:
    appveyor_repo_tag: false        # deploy on tag push only
