image: Visual Studio 2022

install:
  - set QTDIR=C:\Qt\5.15.2\mingw81_64
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\mingw64\bin
  - choco install -y InnoSetup

build_script:
  - qmake big-file-editor.pro
  - mingw64-make
  - del /q release\*.h release\*.cpp release\*.o
  - windeployqt release\big-file-editor.exe
  
after_build:
  - iscc big-file-editor-installer.iss
  - move Output\setupbigfileeditor.exe .

artifacts:
 - path: setupbigfileeditor.exe

deploy:
  description: 'Windows Release'
  provider: GitHub
  auth_token:
    secure: DfVhtXbEs+QEXip7f+Pt9Yon1UeYhlFnJpcY9yu3rhyg4bIOe7vUwEC5+zMbQTJt # your encrypted token from GitHub
  artifact: /.*\.exe/
  on:
    appveyor_repo_tag: false        # deploy on tag push only
